Update

diff --git a/Makefile.minikube b/Makefile.minikube
--- a/Makefile.minikube
+++ b/Makefile.minikube
@@ -1,13 +1,11 @@
-.DEFAULT_GOAL := all
-
 .PHONY: all
-all: setup minikube install-ingress-nginx # install-prometheus
+all: minikube install-ingress-nginx # install-prometheus
 	echo ""
 	echo "URL: 'http://localhost:8080'"
 
 .PHONY: ready
-ready:
-	if [[ "$$(minikube status -f'{{.Kubelet}}'|xargs)" == "Stopped" ]];then echo "Minikube not running !"; exit 1; fi
+ready: setup
+	if [[ "$$(minikube status -f'{{.Kubelet}}'|xargs)" != "Running" ]];then echo "Minikube not running !"; exit 1; fi
 
 .PHONY: setup
 setup:
@@ -18,6 +16,11 @@ setup:
 	if ! [ -x "$$(command -v helm)" ]; then \
 		curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash; \
 	fi
+	if ! [ -x "$$(command -v minikube)" ]; then \
+		curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64; \
+	        sudo install minikube-linux-amd64 /usr/local/bin/minikube; \
+		rm -rf minikube-linux-amd64; \
+	fi
 	#source <(kubectl completion zsh)
 	alias k="kubectl"
 
@@ -27,11 +30,6 @@ minikube: setup
 	echo "You are about to create minikube cluster."
 	echo "Are you sure? (Press Enter to continue or Ctrl+C to abort) "
 	read _
-	if ! [ -x "$$(command -v minikube)" ]; then \
-		curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64; \
-	        sudo install minikube-linux-amd64 /usr/local/bin/minikube; \
-		rm -rf minikube-linux-amd64; \
-	fi
 	eval $$(minikube docker-env --unset) || true
 	minikube config set WantUpdateNotification false
 	MINIKUBE_IN_STYLE=0 minikube start \
@@ -71,7 +69,7 @@ install-prometheus:
 	kubectl wait deployment prometheus-server -n monitoring --for condition=Available=True --timeout=90s
 	helm list -n monitoring
 	#minikube service -n monitoring prometheus-server &
-	killall kubectl || kubectl -n monitoring port-forward svc/prometheus-server 9090:80 &
+	#killall kubectl || kubectl -n monitoring port-forward svc/prometheus-server 9090:80 &
 
 .PHONY: install-ingress-nginx
 install-ingress-nginx:
@@ -113,7 +111,7 @@ get-events: ready
 	kubectl get events --sort-by=.metadata.creationTimestamp
 
 .PHONY: clean
-clean:
+clean: ## Clean up
 	echo ":: $@ ::"
 	echo "You are about to stop minikube cluster."
 	echo "Are you sure? (Press Enter to continue or Ctrl+C to abort) "
